name: Publish

on:
  realease:
    types:
      - released

  workflow_dispatch:

jobs:
  deploy:
    strategy:
      matrix:
        os: [ubuntu-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Install Node.js
          uses: actions/setup-node@v2
          with:
            node-version: "14"
        - run: npm ci
        - name: Publish
          run: npm run deploy
          env:
            VSCE_PAT: ${{ secrets.VSCE_PAT}}
